<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class TrxStatusTorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('trx_status_tor')->insert([
            [
                'id_status' => '1',
                'id_tor' => '1',
                'create_by' => '1',
                'k_judul' => 'OK',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-02-23 11:02:29',
                'updated_at' => '2022-02-23 00:00:00',
            ],
            [
                'id_status' => '2',
                'id_tor' => '1',
                'create_by' => '1',
                'k_judul' => 'OK',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-02-25 11:02:29',
                'updated_at' => '2022-02-25 00:00:00',
            ],
            [
                'id_status' => '1',
                'id_tor' => '3',
                'create_by' => '1',
                'k_judul' => '',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 11:39:43',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id_status' => '1',
                'id_tor' => '9',
                'create_by' => '1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:07:39',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id_status' => '2',
                'id_tor' => '9',
                'create_by' => '6',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:12:21',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id_status' => '3',
                'id_tor' => '9',
                'create_by' => '4',
                'k_judul' => '-',
                'k_tujuan' => 'kurang spesifik !',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 18:41:23',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id_status' => '3',
                'id_tor' => '9',
                'create_by' => '3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 17:09:25',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '3',
                'id_tor' => '9',
                'create_by' => '5',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => 'alamat mitra?',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 17:15:21',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '1',
                'id_tor' => '9',
                'create_by' => '1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 19:18:08',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '5',
                'id_tor' => '9',
                'create_by' => '1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 21:26:02',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '4',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:09:14',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:10:19',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '5',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:10:44',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id_status' => '2',
                'id_tor' => '3',
                'create_by' => '1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-02 13:43:00',
                'updated_at' => '2022-04-02 00:00:00',
            ],
            [
                'id_status' => '4',
                'id_tor' => '3',
                'create_by' => '4',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-07-02 17:00:00',
                'updated_at' => '2022-07-02 00:00:00',
            ],
            [
                'id_status' => '4',
                'id_tor' => '3',
                'create_by' => '3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-07-02 17:00:00',
                'updated_at' => '2022-07-02 00:00:00',
            ],
            [
                'id_status' => '4',
                'id_tor' => '3',
                'create_by' => '5',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-07-02 17:00:00',
                'updated_at' => '2022-07-02 00:00:00',
            ],
        ]);
    }
}
